# На момент завершения работы над курсом версия линтера:
# golangci-lint has version 1.45.2 built from 8bdc4d3f on 2022-03-24T11:51:26Z

run:
  skip-dirs-use-default: false
  tests: true

issues:
  max-same-issues: 0

  exclude:
    - G107 # Potential HTTP request made with variable url
    - G404 # Weak random number generator
    - SA9003 # Empty branch

  exclude-rules:
    - source: .*github\.com/golang-ninja-courses/error-handling-mastery # Imports
      linters:
        - lll

    - source: //go:generate
      linters:
        - lll

    - path: examples/03-go-errors-concept/errorf-\d/main\.go
      linters:
        - govet

    - path: examples/04-non-standard-modules/pkg-wrap-vs-fmt-3
      linters:
        - govet

    - path: examples/05-errors-best-practices/ruleguard-wrap
      linters:
        - deadcode
        - unused

    - path: examples/08-future-of-errors-in-go2
      linters:
        - deadcode
        - unused

    - path: tasks
      linters:
        - typecheck

    - path: _test\.go
      linters:
        - dupl
        - funlen
        - lll

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/golang-ninja-courses/error-handling-mastery)

  lll:
    line-length: 130

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - varcheck
    - wastedassign
    - whitespace
